### PR TITLE
Add google analytics tracking snippet

### PR DESCRIPTION
**Pull request by dvnkshl**
https://linear.app/trychec/issue/CHEC-1536/add-ga-tracking-to-chopchop

Worked on this quickly with Kyle, adds Google Analytics tracking snippet to _index.js

### CODE REVIEW

**Review by robbieaverill — CHANGES_REQUESTED** [review]
Can you please document what this is, how consumers of this repository can change it (from our key to theirs) and add some conditions to prevent React from rendering script tags if the environment variable isn't defined?

**Comment by notrab** [comment]
It's also worth noting that route changes won't be tracked here either. You'll need to send the current URL to `pageview` method on the google tag.

Although you can include the tag conditionally, if you don't provide a a key then any calls to functions will just fallthrough.

**Comment by robbieaverill** [comment]
Maybe the better approach here is to leave the environment variable empty, make the script tag conditional on it existing, then put our key into our Vercel project so it's not part of this repo at all

**Comment by robbieaverill** [comment]
Feel free to reopen when this is ready to review

**Review by robbieaverill — COMMENTED** [review]
Hey @notrab, can you add something that prevents the GA tracking from executing when no GA tracking ID has been defined in the environment variable please?

**Comment by notrab** [comment]
@robbieaverill GA won’t be executed if no ID is provided.

**Comment by robbieaverill** [comment]
Is that something internal to the GA library? Correct me if I'm wrong, but the DOM will still load and contain unwanted GA scripts

**Comment by notrab** [comment]
@robbieaverill it would still load the script, but it wouldn't do anything internally.

I've updated to satisfy the requirements here.

**Review by robbieaverill — APPROVED** [review]
Thanks!

**Comment by robbieaverill** [comment]
Still needs docs, but that can be done as a follow up @dvnkshl

**Comment by notrab** [comment]
I've updated the README to contain a short note on this.

**Comment by robbieaverill** [comment]
Thanks @notrab 🙂

**Pull request merged**
